version: 2
jobs:
  build:
    docker:
      - image: node
    steps:
    - run:
        command: |-
              cd ..
              npm install
              ./node_modules/.bin/eslint index.js index.d.ts
